use crate::http::{Request, Response};
use crate::middleware::session;

/// Number of leading zero bits required in a valid PoW solution.
/// At difficulty 20, a browser must compute ~1 million SHA-256
/// hashes on average. At WASM speeds (~10M hashes/sec) this
/// takes ~100ms — imperceptible to a human, expensive at scale.
/// → Open question: make this configurable via environment variable
const DIFFICULTY: u32 = 20;

/// How long a challenge nonce is valid in seconds.
/// After this window, the challenge must be re-requested.
const CHALLENGE_TTL_SECS: u64 = 300; // 5 minutes

/// A parsed PoW solution submission from the browser.
struct PowSubmission {
    /// The server-issued challenge nonce.
    nonce: String,
    /// The HMAC signature over the nonce, proving server issued it.
    nonce_sig: String,
    /// The candidate value the browser found that satisfies difficulty.
    candidate: u64,
}

/// Verify a PoW solution submitted via POST /pow/verify.
/// Called by router.rs when method=POST, path=/pow/verify.
///
/// On success: returns a 302 redirect with a session cookie.
/// On failure: returns a 400 or 403 with no cookie.
pub fn verify(request: &Request) -> Response {
    // Parse the submission from the request body.
    let submission = match parse_submission(&request.body) {
        Some(s) => s,
        None => return bad_submission(),
    };

    // Verify the nonce was issued by this server.
    // Prevents forged challenges submitted directly to /pow/verify.
    if !verify_nonce_signature(&submission.nonce, &submission.nonce_sig) {
        return bad_submission();
    }

    // Verify the nonce has not expired.
    if nonce_is_expired(&submission.nonce) {
        return expired_challenge();
    }

    // Verify the candidate satisfies the difficulty requirement.
    // This is the actual PoW check — does SHA-256(nonce + candidate)
    // have DIFFICULTY leading zero bits?
    if !solution_is_valid(&submission.nonce, submission.candidate) {
        return bad_submission();
    }

    // Valid solution — issue a session cookie and redirect.
    let cookie = match session::issue_cookie() {
        Some(c) => c,
        None => {
            // SESSION_SECRET not configured — server misconfiguration.
            // Return 500 rather than silently granting access.
            return Response {
                status: 500,
                reason: "Internal Server Error",
                headers: Vec::new(),
                body: b"Server configuration error".to_vec(),
            };
        }
    };

    // 302 redirect to the index page.
    // The session cookie grants access on the next request.
    Response {
        status: 302,
        reason: "Found",
        headers: vec![
            ("Location".to_string(), "/".to_string()),
            ("Set-Cookie".to_string(), cookie),
        ],
        body: Vec::new(),
    }
}

/// Generate a new challenge for the browser to solve.
/// Returns (nonce, signature) — both are sent to the browser
/// in the challenge page. The browser submits them back with
/// its solution so the server can verify authenticity.
pub fn generate_challenge() -> Option<(String, String)> {
    let secret = std::env::var("SESSION_SECRET").ok()?;

    // Nonce format: timestamp.random_hex
    // Timestamp allows expiry checking.
    // Random bytes prevent pre-computation.
    let timestamp = current_unix_time();
    let random = generate_random_hex();
    let nonce = format!("{}.{}", timestamp, random);

    // Sign the nonce so we can verify it was server-issued.
    let signature = hmac_hex(secret.as_bytes(), nonce.as_bytes());

    Some((nonce, signature))
}

/// Parse the PoW submission from the POST body.
/// Expected format: nonce=...&nonce_sig=...&candidate=...
/// Returns None if any field is missing or malformed.
fn parse_submission(body: &[u8]) -> Option<PowSubmission> {
    let body_str = std::str::from_utf8(body).ok()?;

    let mut nonce = None;
    let mut nonce_sig = None;
    let mut candidate = None;

    for pair in body_str.split('&') {
        if let Some((k, v)) = pair.split_once('=') {
            match k {
                "nonce"      => nonce      = Some(v.to_string()),
                "nonce_sig"  => nonce_sig  = Some(v.to_string()),
                "candidate"  => candidate  = v.parse::<u64>().ok(),
                _            => {} // ignore unknown fields
            }
        }
    }

    Some(PowSubmission {
        nonce: nonce?,
        nonce_sig: nonce_sig?,
        candidate: candidate?,
    })
}

/// Verify the nonce HMAC signature.
/// Proves the nonce was generated by this server.
fn verify_nonce_signature(nonce: &str, provided_sig: &str) -> bool {
    let secret = match std::env::var("SESSION_SECRET") {
        Ok(s) => s,
        Err(_) => return false,
    };

    let expected = hmac_hex(secret.as_bytes(), nonce.as_bytes());

    // Constant-time comparison — same reasoning as in session.rs.
    constant_time_eq(expected.as_bytes(), provided_sig.as_bytes())
}

/// Check whether the nonce has exceeded its TTL.
/// Nonce format: timestamp.random_hex — parse the timestamp.
fn nonce_is_expired(nonce: &str) -> bool {
    let timestamp_str = match nonce.split_once('.') {
        Some((ts, _)) => ts,
        None => return true, // malformed nonce, treat as expired
    };

    let issued_at: u64 = match timestamp_str.parse() {
        Ok(t) => t,
        Err(_) => return true,
    };

    current_unix_time().saturating_sub(issued_at) > CHALLENGE_TTL_SECS
}

/// Verify the PoW solution satisfies the difficulty requirement.
/// Computes SHA-256(nonce + "." + candidate) and checks that the
/// result has at least DIFFICULTY leading zero bits.
fn solution_is_valid(nonce: &str, candidate: u64) -> bool {
    let input = format!("{}.{}", nonce, candidate);
    let hash = sha256(input.as_bytes());

    // Count leading zero bits across the hash bytes.
    let mut zero_bits = 0u32;
    for byte in &hash {
        if *byte == 0 {
            zero_bits += 8;
        } else {
            // Count leading zeros in this byte.
            zero_bits += byte.leading_zeros();
            break;
        }
    }

    zero_bits >= DIFFICULTY
}

/// 400 response for a malformed or invalid submission.
fn bad_submission() -> Response {
    Response {
        status: 400,
        reason: "Bad Request",
        headers: Vec::new(),
        body: b"Invalid PoW submission".to_vec(),
    }
}

/// 403 response for an expired challenge.
fn expired_challenge() -> Response {
    Response {
        status: 403,
        reason: "Forbidden",
        headers: Vec::new(),
        body: b"Challenge expired. Please refresh and try again.".to_vec(),
    }
}

/// Current Unix timestamp in seconds.
fn current_unix_time() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("System time before Unix epoch")
        .as_secs()
}

/// Generate 16 random hex bytes using /dev/urandom.
/// Pure std — no rand crate.
fn generate_random_hex() -> String {
    use std::io::Read;
    let mut buf = [0u8; 16];
    std::fs::File::open("/dev/urandom")
        .expect("Cannot open /dev/urandom")
        .read_exact(&mut buf)
        .expect("Cannot read from /dev/urandom");
    buf.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Compute HMAC-SHA256 and return as a hex string.
/// Duplicated from session.rs — shared crypto utilities
/// will be extracted to a crypto module in a future refactor.
/// → Future issue: extract shared crypto to crypto.rs
fn hmac_hex(key: &[u8], message: &[u8]) -> String {
    let digest = hmac_sha256(key, message);
    digest.iter().map(|b| format!("{:02x}", b)).collect()
}

/// HMAC-SHA256 — duplicated from session.rs pending extraction.
fn hmac_sha256(key: &[u8], message: &[u8]) -> [u8; 32] {
    const BLOCK_SIZE: usize = 64;
    const OPAD: u8 = 0x5c;
    const IPAD: u8 = 0x36;

    let mut k_prime = [0u8; BLOCK_SIZE];
    if key.len() > BLOCK_SIZE {
        let hashed = sha256(key);
        k_prime[..32].copy_from_slice(&hashed);
    } else {
        k_prime[..key.len()].copy_from_slice(key);
    }

    let mut inner_input = Vec::with_capacity(BLOCK_SIZE + message.len());
    for b in &k_prime { inner_input.push(b ^ IPAD); }
    inner_input.extend_from_slice(message);
    let inner_hash = sha256(&inner_input);

    let mut outer_input = Vec::with_capacity(BLOCK_SIZE + 32);
    for b in &k_prime { outer_input.push(b ^ OPAD); }
    outer_input.extend_from_slice(&inner_hash);

    sha256(&outer_input)
}

/// SHA-256 — duplicated from session.rs pending extraction.
fn sha256(message: &[u8]) -> [u8; 32] {
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
        0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
    ];
    let k: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
        0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
        0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
        0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
        0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
        0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
        0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
        0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
        0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
        0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
        0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
        0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
        0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
        0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    ];

    let bit_len = (message.len() as u64).wrapping_mul(8);
    let mut padded = message.to_vec();
    padded.push(0x80);
    while padded.len() % 64 != 56 { padded.push(0x00); }
    padded.extend_from_slice(&bit_len.to_be_bytes());

    for chunk in padded.chunks(64) {
        let mut w = [0u32; 64];
        for i in 0..16 {
            w[i] = u32::from_be_bytes([
                chunk[i*4], chunk[i*4+1],
                chunk[i*4+2], chunk[i*4+3],
            ]);
        }
        for i in 16..64 {
            let s0 = w[i-15].rotate_right(7)
                ^ w[i-15].rotate_right(18)
                ^ (w[i-15] >> 3);
            let s1 = w[i-2].rotate_right(17)
                ^ w[i-2].rotate_right(19)
                ^ (w[i-2] >> 10);
            w[i] = w[i-16].wrapping_add(s0)
                .wrapping_add(w[i-7])
                .wrapping_add(s1);
        }

        let [mut a, mut b, mut c, mut d,
             mut e, mut f, mut g, mut hh] = h;
        for i in 0..64 {
            let s1 = e.rotate_right(6)
                ^ e.rotate_right(11)
                ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let temp1 = hh.wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(k[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2)
                ^ a.rotate_right(13)
                ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let temp2 = s0.wrapping_add(maj);
            hh = g; g = f; f = e;
            e = d.wrapping_add(temp1);
            d = c; c = b; b = a;
            a = temp1.wrapping_add(temp2);
        }
        h[0] = h[0].wrapping_add(a);
        h[1] = h[1].wrapping_add(b);
        h[2] = h[2].wrapping_add(c);
        h[3] = h[3].wrapping_add(d);
        h[4] = h[4].wrapping_add(e);
        h[5] = h[5].wrapping_add(f);
        h[6] = h[6].wrapping_add(g);
        h[7] = h[7].wrapping_add(hh);
    }

    let mut digest = [0u8; 32];
    for (i, word) in h.iter().enumerate() {
        digest[i*4..(i+1)*4].copy_from_slice(&word.to_be_bytes());
    }
    digest
}

/// Constant-time comparison — duplicated from session.rs.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() { return false; }
    let result: u8 = a.iter()
        .zip(b.iter())
        .fold(0u8, |acc, (x, y)| acc | (x ^ y));
    result == 0
}
